// <auto-generated />
using System;
using ECommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251116153116_ProductImagesAdded2")]
    partial class ProductImagesAdded2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Core.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AddressGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBillingAddress")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeliveryAddress")
                        .HasColumnType("bit");

                    b.Property<string>("OpenAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 529, DateTimeKind.Local).AddTicks(8589),
                            Email = "admin@gmail.com",
                            IsActive = true,
                            IsAdmin = true,
                            Name = "test",
                            Password = "123456",
                            Surname = "user",
                            UserGuid = new Guid("274435be-5a4e-49f9-92c7-7f132a67ef8a"),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 530, DateTimeKind.Local).AddTicks(9878),
                            Email = "yelda@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Name = "Yelda",
                            Password = "123456",
                            Surname = "Kuru",
                            UserGuid = new Guid("d02930bc-271e-45ff-86a2-cf39ef5c7e30"),
                            UserName = "yelda"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 530, DateTimeKind.Local).AddTicks(9898),
                            Email = "ahmet@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Name = "Ahmet",
                            Password = "654321",
                            Surname = "Demir",
                            UserGuid = new Guid("df08910a-8e9e-4aa3-b3c9-1b7cf81a82b7"),
                            UserName = "ahmet"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 530, DateTimeKind.Local).AddTicks(9910),
                            Email = "elif@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Name = "Elif",
                            Password = "123123",
                            Surname = "Yılmaz",
                            UserGuid = new Guid("0965ab76-bafe-4441-9832-6eee4140422b"),
                            UserName = "elif"
                        });
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 531, DateTimeKind.Local).AddTicks(6863),
                            IsActive = false,
                            Name = "Asus",
                            OrderNo = 0
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 531, DateTimeKind.Local).AddTicks(7180),
                            IsActive = false,
                            Name = "HP",
                            OrderNo = 0
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 531, DateTimeKind.Local).AddTicks(7181),
                            IsActive = false,
                            Name = "Sony",
                            OrderNo = 0
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 531, DateTimeKind.Local).AddTicks(7182),
                            IsActive = false,
                            Name = "MSI",
                            OrderNo = 0
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 531, DateTimeKind.Local).AddTicks(7183),
                            IsActive = false,
                            Name = "Logitech",
                            OrderNo = 0
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 531, DateTimeKind.Local).AddTicks(7184),
                            IsActive = false,
                            Name = "Apple",
                            OrderNo = 0
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 531, DateTimeKind.Local).AddTicks(7184),
                            IsActive = false,
                            Name = "Samsung",
                            OrderNo = 0
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 531, DateTimeKind.Local).AddTicks(7185),
                            IsActive = false,
                            Name = "Dell",
                            OrderNo = 0
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 531, DateTimeKind.Local).AddTicks(7186),
                            IsActive = false,
                            Name = "Canon",
                            OrderNo = 0
                        });
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTopMenu")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 532, DateTimeKind.Local).AddTicks(763),
                            IsActive = true,
                            IsTopMenu = true,
                            Name = "Elektronik",
                            OrderNo = 1,
                            ParentId = 0
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 532, DateTimeKind.Local).AddTicks(1386),
                            IsActive = true,
                            IsTopMenu = true,
                            Name = "Bilgisayar",
                            OrderNo = 2,
                            ParentId = 0
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 532, DateTimeKind.Local).AddTicks(1388),
                            IsActive = true,
                            IsTopMenu = false,
                            Name = "Monitör",
                            OrderNo = 3,
                            ParentId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 532, DateTimeKind.Local).AddTicks(1389),
                            IsActive = true,
                            IsTopMenu = false,
                            Name = "Klavye",
                            OrderNo = 4,
                            ParentId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 532, DateTimeKind.Local).AddTicks(1390),
                            IsActive = true,
                            IsTopMenu = false,
                            Name = "Konsol",
                            OrderNo = 5,
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 532, DateTimeKind.Local).AddTicks(1392),
                            IsActive = true,
                            IsTopMenu = false,
                            Name = "Aksesuar",
                            OrderNo = 6,
                            ParentId = 0
                        });
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderState")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHome")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 2,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 533, DateTimeKind.Local).AddTicks(4204),
                            Description = "15.6 inç Full HD, Ryzen 7 işlemci, 16 GB RAM, 512 GB SSD",
                            IsActive = true,
                            IsHome = true,
                            Name = "Asus TUF Gaming Laptop",
                            OrderNo = 1,
                            Price = 32999.90m,
                            ProductCode = "ASUS-TUF-01",
                            Stock = 25
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CategoryId = 2,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 533, DateTimeKind.Local).AddTicks(5362),
                            Description = "13.3 inç, Intel i5, 8 GB RAM, 256 GB SSD",
                            IsActive = true,
                            IsHome = false,
                            Name = "HP Pavilion Laptop",
                            OrderNo = 2,
                            Price = 21499.50m,
                            ProductCode = "HP-PAV-02",
                            Stock = 18
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            CategoryId = 5,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 533, DateTimeKind.Local).AddTicks(5365),
                            Description = "825 GB SSD, DualSense kumanda dahil",
                            IsActive = true,
                            IsHome = true,
                            Name = "Sony PlayStation 5",
                            OrderNo = 3,
                            Price = 25999.00m,
                            ProductCode = "SONY-PS5",
                            Stock = 10
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            CategoryId = 3,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 533, DateTimeKind.Local).AddTicks(5376),
                            Description = "27 inç, 165Hz, 1ms, kavisli oyun monitörü",
                            IsActive = true,
                            IsHome = false,
                            Name = "MSI Optix Monitör",
                            OrderNo = 4,
                            Price = 8999.99m,
                            ProductCode = "MSI-MON-04",
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 5,
                            CategoryId = 4,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 533, DateTimeKind.Local).AddTicks(5378),
                            Description = "RGB aydınlatmalı, suya dayanıklı, oyun klavyesi",
                            IsActive = true,
                            IsHome = false,
                            Name = "Logitech G213 Klavye",
                            OrderNo = 5,
                            Price = 2499.90m,
                            ProductCode = "LOGI-KLAV-05",
                            Stock = 40
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 6,
                            CategoryId = 2,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 533, DateTimeKind.Local).AddTicks(5381),
                            Description = "13.3 inç Retina, M1 çip, 8 GB RAM, 256 GB SSD",
                            IsActive = true,
                            IsHome = true,
                            Name = "Apple MacBook Air",
                            OrderNo = 6,
                            Price = 23999.00m,
                            ProductCode = "APPLE-MBA-06",
                            Stock = 12
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 7,
                            CategoryId = 1,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 533, DateTimeKind.Local).AddTicks(5382),
                            Description = "11 inç, Snapdragon 865+, 6 GB RAM, 128 GB depolama",
                            IsActive = true,
                            IsHome = false,
                            Name = "Samsung Galaxy Tab S7",
                            OrderNo = 7,
                            Price = 10999.90m,
                            ProductCode = "SAMSUNG-TAB-07",
                            Stock = 20
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 8,
                            CategoryId = 2,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 533, DateTimeKind.Local).AddTicks(5384),
                            Description = "13.4 inç FHD+, Intel i7, 16 GB RAM, 512 GB SSD",
                            IsActive = true,
                            IsHome = true,
                            Name = "Dell XPS 13 Laptop",
                            OrderNo = 8,
                            Price = 27999.50m,
                            ProductCode = "DELL-XPS13-08",
                            Stock = 14
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 9,
                            CategoryId = 1,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 533, DateTimeKind.Local).AddTicks(5386),
                            Description = "24.1 MP, 4K video, döndürülebilir ekran",
                            IsActive = true,
                            IsHome = false,
                            Name = "Canon EOS M50 Kamera",
                            OrderNo = 9,
                            Price = 7499.99m,
                            ProductCode = "CANON-EOSM50-09",
                            Stock = 22
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 3,
                            CategoryId = 6,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 533, DateTimeKind.Local).AddTicks(5388),
                            Description = "Gürültü engelleme, Bluetooth 5.3, 30 saat pil",
                            IsActive = true,
                            IsHome = false,
                            Name = "Sony WH-1000XM5 Kulaklık",
                            OrderNo = 10,
                            Price = 9999.90m,
                            ProductCode = "SONY-WH1000XM5",
                            Stock = 25
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 1,
                            CategoryId = 4,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 533, DateTimeKind.Local).AddTicks(5390),
                            Description = "RGB mekanik oyun klavyesi, dayanıklı tuş yapısı",
                            IsActive = true,
                            IsHome = false,
                            Name = "Asus ROG Klavye",
                            OrderNo = 11,
                            Price = 3499.99m,
                            ProductCode = "ASUS-ROG-KLAV",
                            Stock = 30
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 4,
                            CategoryId = 6,
                            CreateDate = new DateTime(2025, 11, 16, 18, 31, 15, 533, DateTimeKind.Local).AddTicks(5392),
                            Description = "7200 DPI, ergonomik tasarım, RGB ışıklandırma",
                            IsActive = true,
                            IsHome = false,
                            Name = "MSI Gaming Mouse",
                            OrderNo = 12,
                            Price = 1599.50m,
                            ProductCode = "MSI-MOUSE-12",
                            Stock = 35
                        });
                });

            modelBuilder.Entity("ECommerce.Core.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bottom")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Name")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Link")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Address", b =>
                {
                    b.HasOne("ECommerce.Core.Entities.AppUser", "AppUser")
                        .WithMany("Addresses")
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Order", b =>
                {
                    b.HasOne("ECommerce.Core.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.OrderLine", b =>
                {
                    b.HasOne("ECommerce.Core.Entities.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Product", b =>
                {
                    b.HasOne("ECommerce.Core.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId");

                    b.HasOne("ECommerce.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.ProductImage", b =>
                {
                    b.HasOne("ECommerce.Core.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.AppUser", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("ECommerce.Core.Entities.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
